In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [3]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [11]:

np.linalg.det(a)

-9.51619735392994e-16

In [12]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [13]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [14]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
a=np.array([1,2,3,4,5,6,7,8,9,10,4,6])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  6])

In [34]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,4,6])
a
           

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  6])

In [32]:
len(a)

12

In [36]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  6]])

In [37]:
b=np.resize(a,(3,4))

In [38]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  6]])

In [39]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  6])]

In [41]:
arr=np.array([1,2,3,4,5,6])

In [43]:
b=arr.view()

In [44]:
b[0]=20

In [45]:
arr,b

(array([20,  2,  3,  4,  5,  6]), array([20,  2,  3,  4,  5,  6]))

In [46]:
c=arr.copy()

In [47]:
c[2]=33

In [48]:
arr,c

(array([20,  2,  3,  4,  5,  6]), array([20,  2, 33,  4,  5,  6]))