In [1]:
import numpy as np

In [10]:
a=[1,2,3,4]
b=[5,6,7,8]
[a[i]+b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [15]:
import numpy as np
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [21]:
np.array([[1,2,3],[4,5,6]]).shape


(2, 3)

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [57]:
np.eye(3,3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [63]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [67]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

